CLASS zcl_34_square_log_c403 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES zif_06_fm_log_c403 .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_34_square_log_c403 IMPLEMENTATION.


  METHOD zif_06_fm_log_c403~draw_figure.
    rv_shape = 'Square'.
  ENDMETHOD.
ENDCLASS.
