CLASS zcl_08_friends_log_c403 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_09_friends_her_log_c403.

  PUBLIC SECTION.
  PROTECTED SECTION.

    DATA: protected_attr TYPE string.

  PRIVATE SECTION.

    DATA: warehouse TYPE string.

ENDCLASS.



CLASS ZCL_08_FRIENDS_LOG_C403 IMPLEMENTATION.
ENDCLASS.
